Book
vinmash22/Employee-book pull request #1
Opened 2023-02-17 21:50 UTC by vinmash22

Попыталась выполнить самый сложный вариант:)

2023-02-18 17:26 UTC, alekseykoshelev requested changes

2023-02-18 17:26 UTC, alekseykoshelev commented on src/Employee.java
> +        return idCounter;
Тут можно напрямую к полю обращаться, геттер немного лишний.

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                employees[i].setSalary(94256);
В целом тут все правильно, хорошо бы еще перенести зарплату и отдел в аргументы

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +            System.out.println("Сотрудник " + element.getFullName() + ", проиндексированная зарплата: " + indexedSalary + " рублей");
Тут нужно использовать сеттер, чтобы обновить зарплату каждому сотруднику

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        System.out.println("Максимальная зарплата составила " + max + " рублей");
Там по заданию нужно найти именно сотрудника, а не только само значение

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +        System.out.println("Максимальная зарплата по отделу " + departmentNumber + " составила " + max + " рублей");
Аналогичный момент с сотрудниками как и выше

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                    System.out.println("Сотрудник " + employees[i].getFullName() + ", зарплата: " + employees[i].getSalary() + " рублей");
А вывод ведь одинаковый, можно тогда убрать if

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                System.out.println("Сотрудник " + element.getFullName() + ", проиндексированная зарплата: " + indexedSalary + " рублей");
Аналогично надо использовать сеттер

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +            if (employees[i].getSalary() < number) {
Тут еще надо добавить проверку на `null`. Ведь какие-то сотрудники могут быть удалены.

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +            if (employees[i].getSalary() < number) {
Это относится ко всем методам, везде надо сделать проверку)

2023-02-18 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +                    if (i == employees.length - 1) {
Тут if лишний опять, ведь код одинаковый внутри и вне него

2023-02-21 17:26 UTC, alekseykoshelev commented on src/EmployeeBook.java
> +            if (element != null && empWithMinSalary == null || element != null && element.getSalary() < empWithMinSalary.getSalary()) {
Тут можно немного сократить, вынести за скобки условие так скажем) 
`element != null && (empWithMinSalary == null || element.getSalary() < empWithMinSalary.getSalary())`

2023-02-22 16:42 UTC, vinmash22 commented on src/EmployeeBook.java
> +            if (element != null && empWithMinSalary == null || element != null && element.getSalary() < empWithMinSalary.getSalary()) {
о, как в математике:) спасибо:)

2023-02-28 17:47 UTC, merged